// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201010170854_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Repository.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("BurthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SexId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("SexId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fab43ad7-fe6c-4fd2-8267-1d8032600a8f"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1996, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "JOHNATHON",
                            Name = "ALEXIS",
                            PhoneNumber = "7270877602",
                            SexId = 1,
                            Surname = "JARED"
                        },
                        new
                        {
                            Id = new Guid("562f47bc-fe9d-4d04-ab72-ad4ebc0ae3da"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1997, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "EDWINA",
                            Name = "LORRIE",
                            PhoneNumber = "5067441910",
                            SexId = 2,
                            Surname = "BERYL"
                        },
                        new
                        {
                            Id = new Guid("2292c6b7-5aca-4ad0-bcb6-5eabf3c9a8ff"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(2013, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "LUCINDA",
                            Name = "LESSIE",
                            PhoneNumber = "1991743531",
                            SexId = 2,
                            Surname = "JACQUELINE"
                        },
                        new
                        {
                            Id = new Guid("523160c9-fc0b-4b9e-9a0d-fb165c1567ba"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1998, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "JEREMY",
                            Name = "MARCEL",
                            PhoneNumber = "2086671887",
                            SexId = 1,
                            Surname = "GARRY"
                        },
                        new
                        {
                            Id = new Guid("166efc29-f7c3-4dc4-961c-5533e541626c"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(2017, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "RAFAEL",
                            Name = "JOHNNY",
                            PhoneNumber = "7786672658",
                            SexId = 1,
                            Surname = "GERARDO"
                        },
                        new
                        {
                            Id = new Guid("d6f162ff-0d8e-40dc-a5c7-801bac7a1123"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1984, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "CHASITY",
                            Name = "LESSIE",
                            PhoneNumber = "8586913414",
                            SexId = 2,
                            Surname = "BEATRIZ"
                        },
                        new
                        {
                            Id = new Guid("541cd224-f4fb-4459-9dfc-83c8297eaff7"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1976, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "MICKEY",
                            Name = "ROBIN",
                            PhoneNumber = "5434980428",
                            SexId = 1,
                            Surname = "VICENTE"
                        },
                        new
                        {
                            Id = new Guid("ba375c81-d7e5-4815-bb6e-be4bf73e4770"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(2008, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "NETTIE",
                            Name = "LAURA",
                            PhoneNumber = "5786826319",
                            SexId = 2,
                            Surname = "LYNNETTE"
                        },
                        new
                        {
                            Id = new Guid("eebb2e8e-8500-47e7-b1f2-3f6880eaee54"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1954, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "NEAL",
                            Name = "VIRGIL",
                            PhoneNumber = "8597329325",
                            SexId = 1,
                            Surname = "IRVING"
                        },
                        new
                        {
                            Id = new Guid("978c32a9-7c5d-4269-8027-7bcd36fc8c3f"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1953, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "RAYMOND",
                            Name = "MARVIN",
                            PhoneNumber = "3877856019",
                            SexId = 1,
                            Surname = "ELIJAH"
                        },
                        new
                        {
                            Id = new Guid("7c1e872e-1d17-4103-b1e5-76369a75e5aa"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1986, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "ALEXANDER",
                            Name = "DARREL",
                            PhoneNumber = "2759711662",
                            SexId = 1,
                            Surname = "DEWEY"
                        },
                        new
                        {
                            Id = new Guid("f0f8dbb5-e7e6-4ec0-aaaa-788aac5ad631"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1966, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "JAIME",
                            Name = "DARREN",
                            PhoneNumber = "8309906067",
                            SexId = 1,
                            Surname = "LINWOOD"
                        },
                        new
                        {
                            Id = new Guid("7218b9c7-b7a6-4a38-bcb2-42de26d42e56"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1982, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "CLARICE",
                            Name = "PATRICE",
                            PhoneNumber = "5955388947",
                            SexId = 2,
                            Surname = "LOIS"
                        },
                        new
                        {
                            Id = new Guid("fbae2f1d-91f3-4fea-b78d-96738e5d1f49"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(2011, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "KATHERINE",
                            Name = "SALLY",
                            PhoneNumber = "6951344133",
                            SexId = 2,
                            Surname = "CHASITY"
                        },
                        new
                        {
                            Id = new Guid("ceef74c6-a2d1-46d9-87dd-87d0706bfa60"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1980, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "WILEY",
                            Name = "SALVADOR",
                            PhoneNumber = "4611295556",
                            SexId = 1,
                            Surname = "ODELL"
                        },
                        new
                        {
                            Id = new Guid("a5357326-8d97-44e4-8a98-10bb34a61977"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1972, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "EFFIE",
                            Name = "BEULAH",
                            PhoneNumber = "5628459085",
                            SexId = 2,
                            Surname = "CANDICE"
                        },
                        new
                        {
                            Id = new Guid("f54a06f5-5bfd-4594-8921-4a2405c882df"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1958, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "NATALIA",
                            Name = "EUGENIA",
                            PhoneNumber = "5571215100",
                            SexId = 2,
                            Surname = "GLENNA"
                        },
                        new
                        {
                            Id = new Guid("841bf23e-caa1-4377-8ea8-f2ba8dd144ca"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1993, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "ANGELA",
                            Name = "SIERRA",
                            PhoneNumber = "6775290056",
                            SexId = 2,
                            Surname = "NORA"
                        },
                        new
                        {
                            Id = new Guid("a30439f1-4f75-435a-8b48-c251647a1fe3"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1989, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "ROSLYN",
                            Name = "TARA",
                            PhoneNumber = "2668375921",
                            SexId = 2,
                            Surname = "JOANNE"
                        },
                        new
                        {
                            Id = new Guid("b151e1d1-dc9e-4783-b3b2-ab07c1c1602b"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1961, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "LULA",
                            Name = "OFELIA",
                            PhoneNumber = "2324027444",
                            SexId = 2,
                            Surname = "MARCELLA"
                        },
                        new
                        {
                            Id = new Guid("0e0e995e-9be3-47b5-b96d-f926c296129b"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(2017, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "BETTY",
                            Name = "LAVERNE",
                            PhoneNumber = "7489433890",
                            SexId = 2,
                            Surname = "TAMERA"
                        },
                        new
                        {
                            Id = new Guid("ccf0889a-c33f-4b10-aadb-9e72549d456e"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1970, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "BROOKE",
                            Name = "ROSLYN",
                            PhoneNumber = "4772514520",
                            SexId = 2,
                            Surname = "JACLYN"
                        },
                        new
                        {
                            Id = new Guid("7e70b103-68cc-48ff-8a88-262d98eab2cb"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1955, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "ORA",
                            Name = "JUSTINA",
                            PhoneNumber = "6692812740",
                            SexId = 2,
                            Surname = "ESTELLE"
                        },
                        new
                        {
                            Id = new Guid("8e10422d-440c-47a1-ab88-a54656a84179"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(2017, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "JUANITA",
                            Name = "ELIZABETH",
                            PhoneNumber = "9659868146",
                            SexId = 2,
                            Surname = "PAULA"
                        },
                        new
                        {
                            Id = new Guid("98b0a338-a7ef-4fad-9017-aa60b67df726"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1972, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "REX",
                            Name = "WILFREDO",
                            PhoneNumber = "4593964619",
                            SexId = 1,
                            Surname = "TYSON"
                        },
                        new
                        {
                            Id = new Guid("ea8806e1-f32a-4dd7-ac89-185d15c5b455"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1971, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "STEPHANIE",
                            Name = "CHRISTI",
                            PhoneNumber = "3007811468",
                            SexId = 2,
                            Surname = "MELISA"
                        },
                        new
                        {
                            Id = new Guid("9e8f8eb4-68c7-477c-b53c-98928a4ef418"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(2007, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "FLORENCE",
                            Name = "PAIGE",
                            PhoneNumber = "6565214965",
                            SexId = 2,
                            Surname = "RUTHIE"
                        },
                        new
                        {
                            Id = new Guid("90f17a90-5b40-43c5-82f0-cd9685c57ab5"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1993, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "VAN",
                            Name = "HEATH",
                            PhoneNumber = "1877538036",
                            SexId = 1,
                            Surname = "ERROL"
                        },
                        new
                        {
                            Id = new Guid("4d6a5dbe-3443-4356-a509-2787ba157c7d"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1999, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "JULIET",
                            Name = "ALICE",
                            PhoneNumber = "6032456620",
                            SexId = 2,
                            Surname = "FLOSSIE"
                        },
                        new
                        {
                            Id = new Guid("06ecb6b1-28d1-47bb-b8f1-169ec6965946"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1992, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "CEDRIC",
                            Name = "WAYNE",
                            PhoneNumber = "9940431726",
                            SexId = 1,
                            Surname = "ED"
                        },
                        new
                        {
                            Id = new Guid("5e9c99b6-b7fe-4981-974a-b32dfc334afd"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(2009, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "TIFFANY",
                            Name = "LUELLA",
                            PhoneNumber = "3382925989",
                            SexId = 2,
                            Surname = "AIMEE"
                        },
                        new
                        {
                            Id = new Guid("a5afceff-ef61-488d-86a2-e50c999a3673"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(2007, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "DELMAR",
                            Name = "JUNIOR",
                            PhoneNumber = "8251811013",
                            SexId = 1,
                            Surname = "EDGAR"
                        },
                        new
                        {
                            Id = new Guid("ff0ab253-a06c-4ac8-b7c2-90ce559cd6ad"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(2010, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "EUNICE",
                            Name = "INGRID",
                            PhoneNumber = "9859584043",
                            SexId = 2,
                            Surname = "YOUNG"
                        },
                        new
                        {
                            Id = new Guid("24e45e4f-6d77-4ab8-8ef8-de8cce85dc13"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1963, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "ROMEO",
                            Name = "SAM",
                            PhoneNumber = "7469475002",
                            SexId = 1,
                            Surname = "LINWOOD"
                        },
                        new
                        {
                            Id = new Guid("50248e8c-91de-487d-9746-949f758d2bfa"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1973, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "KENNETH",
                            Name = "JAN",
                            PhoneNumber = "8081558051",
                            SexId = 1,
                            Surname = "ALPHONSO"
                        },
                        new
                        {
                            Id = new Guid("1e690e96-7880-4bf5-a8da-5f11b44d7f88"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1979, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "RON",
                            Name = "DONALD",
                            PhoneNumber = "7640487444",
                            SexId = 1,
                            Surname = "THEODORE"
                        },
                        new
                        {
                            Id = new Guid("6e156be6-1041-4035-b760-c80e1f2ed6f5"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1960, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "PETE",
                            Name = "DION",
                            PhoneNumber = "4154775763",
                            SexId = 1,
                            Surname = "PIERRE"
                        },
                        new
                        {
                            Id = new Guid("ea8b9b05-2a9a-4250-9e33-f068f262c908"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1965, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "PENELOPE",
                            Name = "TERRA",
                            PhoneNumber = "9349575505",
                            SexId = 2,
                            Surname = "WINIFRED"
                        },
                        new
                        {
                            Id = new Guid("b6d1122d-7dad-4526-b155-ad9d07edd3d2"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1997, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "LESLIE",
                            Name = "ERIN",
                            PhoneNumber = "2552478454",
                            SexId = 2,
                            Surname = "BROOKE"
                        },
                        new
                        {
                            Id = new Guid("7fb5f305-47c3-4d6c-a097-0425d64c5976"),
                            Address = "Lorem, ipsum dolor Lorem, ipsum dolor",
                            BurthDate = new DateTime(1958, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiddleName = "BENNIE",
                            Name = "CESAR",
                            PhoneNumber = "9337665349",
                            SexId = 1,
                            Surname = "RONALD"
                        });
                });

            modelBuilder.Entity("Repository.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("SexId")
                        .HasColumnType("int");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("SexId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ec77a66-5395-4528-872b-6b93d92b6af9"),
                            MiddleName = "ALBERTO",
                            Name = "MARC",
                            SexId = 1,
                            Speciality = "лор",
                            Surname = "JIMMIE"
                        },
                        new
                        {
                            Id = new Guid("a8f4ee8f-88de-4b78-8aa9-0242ae9b0397"),
                            MiddleName = "OLLIE",
                            Name = "LUISA",
                            SexId = 2,
                            Speciality = "хирург",
                            Surname = "MANDY"
                        },
                        new
                        {
                            Id = new Guid("bf57ce4e-378f-42ed-974c-5561f41fa0e3"),
                            MiddleName = "MAGDALENA",
                            Name = "KIMBERLEY",
                            SexId = 2,
                            Speciality = "хирург",
                            Surname = "JANELL"
                        },
                        new
                        {
                            Id = new Guid("eaa6ebfc-083f-404c-98a9-660d840963e0"),
                            MiddleName = "MELVA",
                            Name = "LACEY",
                            SexId = 2,
                            Speciality = "лор",
                            Surname = "OFELIA"
                        },
                        new
                        {
                            Id = new Guid("f4fc19bf-7c61-47b6-8744-dab753ea9add"),
                            MiddleName = "DIANE",
                            Name = "LILLIAN",
                            SexId = 2,
                            Speciality = "хирург",
                            Surname = "TANISHA"
                        });
                });

            modelBuilder.Entity("Repository.Entities.Sex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Sex");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "мужской"
                        },
                        new
                        {
                            Id = 2,
                            Name = "женский"
                        });
                });

            modelBuilder.Entity("Repository.Entities.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("VisitId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70c75ce3-5088-47c3-83ab-95aac52918f1"),
                            ClientId = new Guid("eebb2e8e-8500-47e7-b1f2-3f6880eaee54"),
                            Diagnosis = "Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor",
                            DoctorId = new Guid("9ec77a66-5395-4528-872b-6b93d92b6af9"),
                            VisitDate = new DateTime(2020, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 2
                        },
                        new
                        {
                            Id = new Guid("06771809-4981-499c-aaf6-5627ab19d98d"),
                            ClientId = new Guid("6e156be6-1041-4035-b760-c80e1f2ed6f5"),
                            Diagnosis = "",
                            DoctorId = new Guid("a8f4ee8f-88de-4b78-8aa9-0242ae9b0397"),
                            VisitDate = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 1
                        },
                        new
                        {
                            Id = new Guid("03d181c9-19ef-4550-a28c-9dad67700f45"),
                            ClientId = new Guid("0e0e995e-9be3-47b5-b96d-f926c296129b"),
                            Diagnosis = "Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor",
                            DoctorId = new Guid("f4fc19bf-7c61-47b6-8744-dab753ea9add"),
                            VisitDate = new DateTime(2020, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 2
                        },
                        new
                        {
                            Id = new Guid("587167cc-1762-427a-8ab7-72433bc4977c"),
                            ClientId = new Guid("541cd224-f4fb-4459-9dfc-83c8297eaff7"),
                            Diagnosis = "",
                            DoctorId = new Guid("9ec77a66-5395-4528-872b-6b93d92b6af9"),
                            VisitDate = new DateTime(2020, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 1
                        },
                        new
                        {
                            Id = new Guid("fad55e74-b907-4a33-9fde-7993afea98de"),
                            ClientId = new Guid("a30439f1-4f75-435a-8b48-c251647a1fe3"),
                            Diagnosis = "Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor",
                            DoctorId = new Guid("f4fc19bf-7c61-47b6-8744-dab753ea9add"),
                            VisitDate = new DateTime(2020, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 2
                        },
                        new
                        {
                            Id = new Guid("3f01dc92-e9ad-4468-9e3c-2c53fad46c53"),
                            ClientId = new Guid("ceef74c6-a2d1-46d9-87dd-87d0706bfa60"),
                            Diagnosis = "Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor",
                            DoctorId = new Guid("bf57ce4e-378f-42ed-974c-5561f41fa0e3"),
                            VisitDate = new DateTime(2020, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 2
                        },
                        new
                        {
                            Id = new Guid("ea4deae0-5d70-4d8e-a143-cab5811393f7"),
                            ClientId = new Guid("ea8806e1-f32a-4dd7-ac89-185d15c5b455"),
                            Diagnosis = "",
                            DoctorId = new Guid("f4fc19bf-7c61-47b6-8744-dab753ea9add"),
                            VisitDate = new DateTime(2020, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 1
                        },
                        new
                        {
                            Id = new Guid("a66fb87d-e3b3-4ebf-a57c-ceb287230337"),
                            ClientId = new Guid("90f17a90-5b40-43c5-82f0-cd9685c57ab5"),
                            Diagnosis = "",
                            DoctorId = new Guid("bf57ce4e-378f-42ed-974c-5561f41fa0e3"),
                            VisitDate = new DateTime(2020, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 1
                        },
                        new
                        {
                            Id = new Guid("c59ef386-8260-41f9-a297-8484d2f4d63a"),
                            ClientId = new Guid("eebb2e8e-8500-47e7-b1f2-3f6880eaee54"),
                            Diagnosis = "Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor",
                            DoctorId = new Guid("bf57ce4e-378f-42ed-974c-5561f41fa0e3"),
                            VisitDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 2
                        },
                        new
                        {
                            Id = new Guid("05f57372-f6b7-4295-8ff0-1cb3660fbebc"),
                            ClientId = new Guid("ceef74c6-a2d1-46d9-87dd-87d0706bfa60"),
                            Diagnosis = "",
                            DoctorId = new Guid("bf57ce4e-378f-42ed-974c-5561f41fa0e3"),
                            VisitDate = new DateTime(2020, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 1
                        },
                        new
                        {
                            Id = new Guid("3b6dac21-e189-416d-a31e-4fab14883598"),
                            ClientId = new Guid("06ecb6b1-28d1-47bb-b8f1-169ec6965946"),
                            Diagnosis = "Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor",
                            DoctorId = new Guid("f4fc19bf-7c61-47b6-8744-dab753ea9add"),
                            VisitDate = new DateTime(2020, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 2
                        },
                        new
                        {
                            Id = new Guid("8d3b39cd-6edd-4c07-874f-4145a7b2411e"),
                            ClientId = new Guid("fbae2f1d-91f3-4fea-b78d-96738e5d1f49"),
                            Diagnosis = "Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor",
                            DoctorId = new Guid("bf57ce4e-378f-42ed-974c-5561f41fa0e3"),
                            VisitDate = new DateTime(2020, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 2
                        },
                        new
                        {
                            Id = new Guid("506143cf-01af-4b00-8615-ea750f1a0201"),
                            ClientId = new Guid("eebb2e8e-8500-47e7-b1f2-3f6880eaee54"),
                            Diagnosis = "Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor",
                            DoctorId = new Guid("9ec77a66-5395-4528-872b-6b93d92b6af9"),
                            VisitDate = new DateTime(2020, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 2
                        },
                        new
                        {
                            Id = new Guid("27ae0445-e961-4364-8eec-973697d85498"),
                            ClientId = new Guid("166efc29-f7c3-4dc4-961c-5533e541626c"),
                            Diagnosis = "Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor",
                            DoctorId = new Guid("f4fc19bf-7c61-47b6-8744-dab753ea9add"),
                            VisitDate = new DateTime(2020, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 2
                        },
                        new
                        {
                            Id = new Guid("9708bc3a-c7ab-4f87-a95d-30d45960118f"),
                            ClientId = new Guid("1e690e96-7880-4bf5-a8da-5f11b44d7f88"),
                            Diagnosis = "Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor",
                            DoctorId = new Guid("f4fc19bf-7c61-47b6-8744-dab753ea9add"),
                            VisitDate = new DateTime(2020, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 2
                        },
                        new
                        {
                            Id = new Guid("29267c3d-33f1-4bfc-86fd-cf3c6e125bc6"),
                            ClientId = new Guid("fbae2f1d-91f3-4fea-b78d-96738e5d1f49"),
                            Diagnosis = "Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor",
                            DoctorId = new Guid("9ec77a66-5395-4528-872b-6b93d92b6af9"),
                            VisitDate = new DateTime(2020, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 2
                        },
                        new
                        {
                            Id = new Guid("0908b0d2-1698-42b3-a20f-77c8ba40e2f6"),
                            ClientId = new Guid("6e156be6-1041-4035-b760-c80e1f2ed6f5"),
                            Diagnosis = "",
                            DoctorId = new Guid("bf57ce4e-378f-42ed-974c-5561f41fa0e3"),
                            VisitDate = new DateTime(2020, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 1
                        },
                        new
                        {
                            Id = new Guid("cc6c3cec-8c08-4a70-9df6-2802f63fe76f"),
                            ClientId = new Guid("a5357326-8d97-44e4-8a98-10bb34a61977"),
                            Diagnosis = "Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor",
                            DoctorId = new Guid("f4fc19bf-7c61-47b6-8744-dab753ea9add"),
                            VisitDate = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 2
                        },
                        new
                        {
                            Id = new Guid("01f47bdc-a323-4d4d-bc1a-776bb152a5ba"),
                            ClientId = new Guid("841bf23e-caa1-4377-8ea8-f2ba8dd144ca"),
                            Diagnosis = "Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor",
                            DoctorId = new Guid("9ec77a66-5395-4528-872b-6b93d92b6af9"),
                            VisitDate = new DateTime(2020, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 2
                        },
                        new
                        {
                            Id = new Guid("3949a1f3-8ca9-4407-a558-91e373d7ad36"),
                            ClientId = new Guid("a5afceff-ef61-488d-86a2-e50c999a3673"),
                            Diagnosis = "Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor Lorem, ipsum dolor",
                            DoctorId = new Guid("a8f4ee8f-88de-4b78-8aa9-0242ae9b0397"),
                            VisitDate = new DateTime(2020, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 2
                        });
                });

            modelBuilder.Entity("Repository.Entities.VisitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("VisitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("VisitTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            VisitName = "первичный"
                        },
                        new
                        {
                            Id = 2,
                            VisitName = "вторичный"
                        });
                });

            modelBuilder.Entity("Repository.Entities.Client", b =>
                {
                    b.HasOne("Repository.Entities.Sex", "Sex")
                        .WithMany("Clients")
                        .HasForeignKey("SexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.Entities.Doctor", b =>
                {
                    b.HasOne("Repository.Entities.Sex", "Sex")
                        .WithMany("Doctors")
                        .HasForeignKey("SexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.Entities.Visit", b =>
                {
                    b.HasOne("Repository.Entities.Client", "Client")
                        .WithMany("Visits")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Doctor", "Doctor")
                        .WithMany("Visits")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Repository.Entities.VisitType", "VisitType")
                        .WithMany("Visits")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
